### ISSUE TITLE
requirejs paths

### ISSUE THREAD

**Issue by jvmlet** [webjars/font-awesome#15]
Hello
Would you please define paths in pom.xml ?
Thanks

**Comment by jamesward** [comment]
I'm not sure if it makes sense to have a RequireJS config in this WebJar because Require doesn't have a standard way to load css and fonts.  You can use loader plugins for that but the user can pick any loader plugin prefix so it would be hard to pick a prefix to put into this config.  Instead, you should use your own custom config when using this WebJar.

We need better docs on how to override the Require config.  There is some info in the Play Framework docs: http://www.webjars.org/documentation

Let me know if that helps.

**Comment by jvmlet** [comment]
Well,I know that it's possible override the config, but the approach is NOT version agnostic. I'll have to tweak the config each time the version of this particular WebJar is updated.
On the other hand, what is wrong to define the path without  loader plugin , as you <b>already do for bootstrap css here https://github.com/webjars/bootstrap/blob/master/pom.xml</b>?
Then the client will require it with requirejs plugin he chooses:
````
require(['css!fontAwesomePath'],function(fa){})

**Comment by jamesward** [comment]
For some reason I had remembered that the way we did it in the bootstrap WebJar didn't actually work when prepending the `css!` loader.  But I'm probably wrong about that.  In which case we can add these.  Do you need the require configs for the fonts of just the `*.css` files?

**Comment by jvmlet** [comment]
James,
Prepending the !css works perfectly well.
I need both fonts and css. 
BTW, I've opened another enhancement here  https://github.com/webjars/webjars-locator/issues/87  that allows user to re-define webjar paths the way he wants.
This feature will probably reduce the number of issues you get.
Thanks for the webjars, it makes the dev live much earthier....
